export const translations = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    ledger: "Ledger & SMS Parser",
    subscriptions: "Subscription Radar",
    savings: "Dynamic Savings",
    simulator: "What-If Sandbox",
    stocks: "Stock Advisor",
    localSandbox: "100% Local Sandbox",
    localSandboxDesc: "All computations, Naive Bayes models, SMS parses, and forecasting parameters are running locally on your device.",
    
    // Dashboard general
    commandCenter: "Financial Command Center",
    welcome: "Welcome back. Here is your local offline financial summary.",
    netWorth: "Net Worth Balance",
    totalInflow: "Total Inflow",
    totalOutflow: "Total Outflow",
    balanceGrowth: "Balance Growth History",
    topCategories: "Top Spending Categories",
    moneyLeak: "Money Leak Radar & Tips",
    forecasting: "30-Day Forecasting Projection",
    forecastingDesc: "Our time-series projection models historical debit velocity to project upcoming daily cash draws. Keep month-end outflows low to avoid deficits.",
    noExpenses: "No expenses recorded yet.",
    noForecast: "Add more transaction logs to build a projection baseline.",
    analyzingHabits: "Analyzing spending habits...",
    noTips: "No saving tips at this time. Keep up the good work!",
    
    // Ledger & SMS
    ledgerTitle: "Transaction Ledger",
    ledgerDesc: "Log spending, verify ML categorization, and parse bank notifications.",
    logManual: "Log Manual Transaction",
    txType: "Transaction Type",
    debit: "Debit (Expense)",
    credit: "Credit (Income)",
    date: "Date",
    description: "Description (Merchant/Source)",
    amount: "Amount ($)",
    category: "Category",
    addTx: "Add Transaction",
    smsTitle: "Bank SMS / Notification Reader",
    smsDesc: "Paste the raw text of your bank notification SMS below. Our offline NLP parser will instantly extract transaction details.",
    parseSMSBtn: "Parse SMS Text",
    parsedPreview: "Parsed Result Preview",
    approveTx: "Approve & Log Transaction",
    ledgerRecords: "Ledger Record Logs",
    properties: "Properties",
    actions: "Actions",
    linkBankBtn: "Link Bank Account (SAMA API)",
    linkingProgress: "Syncing SAMA Open Banking API...",
    linkedStatus: "Synced Accounts:",
    
    // Subscriptions
    subsTitle: "Recurring Subscription Radar",
    subsDesc: "Identify fixed-interval subscriptions, set renewal tracking timers, and flag money leaks.",
    registerSub: "Register Subscription",
    merchantName: "Merchant Name",
    interval: "Interval",
    weekly: "Weekly",
    monthly: "Monthly",
    yearly: "Yearly",
    nextRenewal: "Next Renewal",
    utilityScore: "Utility Score (0-1)",
    saveSub: "Save Subscription",
    subsRecommendations: "Tracked Subscriptions & Recommendations",
    lowUtilityCancel: "Low Utility: Cancel?",
    utilityLevel: "Utility Level",
    renewalCountdown: "Renewal countdown",
    active: "Active",
    paused: "Paused",
    days: "days",

    // Simulator
    simTitle: '"What-If" Decision Simulator',
    simDesc: "Project long-term budget health and cash flow impacts before committing to major expenses or loans.",
    simVariables: "Simulation Variables",
    simName: "Simulation Name",
    oneTimeCost: "One-Time Upfront Cost ($)",
    monthlyCostChange: "Monthly Cost Change ($)",
    monthlyIncomeChange: "Monthly Income Change ($)",
    simHorizon: "Simulation Horizon",
    years1: "1 Year Projection",
    years3: "3 Years Projection",
    years5: "5 Years Projection",
    runProjections: "Run Projections",
    projectedWorth: "Projected Net Worth Comparison",
    decisionImpact: "Decision Impact",
    currentMonthlySavings: "Current Monthly Savings",
    simulatedMonthlySavings: "Simulated Monthly Savings",
    simPrompt: "Input your variables on the left and run the projections sandbox engine.",

    // Stock Advisor
    stockTitle: "Multi-Asset Portfolio Tracker",
    stockDesc: "Track investment values, view real-time allocations, and check local AI Buy/Sell signals.",
    refreshBtn: "Refresh Markets",
    portfolioVal: "Portfolio Market Value",
    costBasis: "Cost Basis",
    unrealizedPnL: "Unrealized Gain/Loss",
    registerAsset: "Register Assets",
    symbol: "Symbol",
    assetName: "Asset Name",
    quantity: "Quantity",
    buyPrice: "Buy Price ($)",
    curPrice: "Current Market Price ($)",
    addAssetBtn: "Add Stock Asset",
    assetAllocation: "Asset Allocation",
    tradingSignals: "Intelligent Trading Signals",
    signalsDesc: "Computed entirely offline: aggregates technical indicators (RSI bounds & 5-day/15-day SMA crossovers) weighted against a local NLP headline sentiment scan.",
    noSignals: "Add stock logs to generate advisor signals.",
    shariahBadge: "Shariah Status",
    compliant: "Compliant",
    nonCompliant: "Non-Compliant",
    complianceCheck: "Shariah Screening Criteria",
    complianceCheckDesc: "Analyzes balance sheet parameters using SAMA guidelines: Debt/Cap < 33%, Interest Cash/Cap < 33%, Impure Income < 5%.",

    // Savings Goals
    savingsTitle: "Dynamic Savings Goals",
    savingsDesc: "Track targeted funds and compute optimal savings percentages dynamically adjusting to cash flows.",
    allocationAdvice: "Saudi Vision 2030 Saving Target Advice",
    recommendedRate: "Your Recommended Savings Rate:",
    formulaExplanation: "Calculated dynamically: adjusts your baseline savings target (20%) based on current month income relative to fixed overhead costs. This preserves cash buffers when expenses swell.",
    createTargetGoal: "Create Target Goal",
    goalTitle: "Goal Title",
    currentSaved: "Current Saved ($)",
    saveGoalBtn: "Save Goal",
    trackedTargets: "Saudi Vision 2030 Savings Targets & Quests",
    savedOf: "saved of",
    addFunds: "Add funds ($)",
    fundGoalBtn: "Fund Goal",
    noGoals: "No active savings goals found. Set up your first savings target on the left panel!",
    gamificationBadges: "Unlocking Financial Quests",
    gamificationDesc: "Incentivize local savings behaviors to align with Saudi Vision 2030 goals. Earn achievements by managing your capital wisely.",
    unlockedAt: "Unlocked on",
    locked: "Locked"
  },
  
  ar: {
    // Navigation
    dashboard: "لوحة التحكم",
    ledger: "دفتر العمليات وقارئ الرسائل",
    subscriptions: "رادار الاشتراكات المتكررة",
    savings: "الادخار الديناميكي",
    simulator: "محاكي القرارات المالية",
    stocks: "مستشار الأسهم والشرعيات",
    localSandbox: "بيئة عمل محلية وآمنة 100%",
    localSandboxDesc: "تتم جميع العمليات الحسابية وتصنيفات الذكاء الاصطناعي وقراءة الرسائل والتحليلات محليًا بالكامل دون مغادرة جهازك.",
    
    // Dashboard general
    commandCenter: "مركز التحكم المالي الذكي",
    welcome: "مرحباً بك مجدداً. إليك ملخصك المالي المحلي والآمن.",
    netWorth: "صافي القيمة المالية",
    totalInflow: "إجمالي الدخل",
    totalOutflow: "إجمالي المصاريف",
    balanceGrowth: "سجل نمو الرصيد المالي",
    topCategories: "أعلى فئات الصرف",
    moneyLeak: "رادار تسرب الأموال ونصائح الادخار",
    forecasting: "توقعات التدفقات المالية لـ 30 يوماً",
    forecastingDesc: "يقوم نموذج السلاسل الزمنية بتحليل سرعة الصرف للتنبؤ بالرصيد المتوقع وتفادي أي عجز مالي قبل حدوثه.",
    noExpenses: "لا توجد مصاريف مسجلة حتى الآن.",
    noForecast: "قم بإضافة المزيد من العمليات لبناء نموذج التوقعات.",
    analyzingHabits: "جاري تحليل سلوكك المالي محلياً...",
    noTips: "رادار الادخار يعمل بكفاءة، لا توجد نصائح تسرب حالياً. واصل العمل الرائع!",
    
    // Ledger & SMS
    ledgerTitle: "سجل المعاملات المالية",
    ledgerDesc: "سجل العمليات المالية يدوياً، تحقق من دقة تصنيف الذكاء الاصطناعي، وقم بتحليل رسائل البنك.",
    logManual: "تسجيل معاملة مالية يدوياً",
    txType: "نوع المعاملة",
    debit: "سحب (مصروف)",
    credit: "إيداع (دخل)",
    date: "التاريخ",
    description: "التفاصيل (التاجر/المصدر)",
    amount: "المبلغ (ريال)",
    category: "الفئة",
    addTx: "إضافة المعاملة",
    smsTitle: "قارئ رسائل البنك والإشعارات",
    smsDesc: "قم بنسخ نص رسالة البنك (SMS) ولصقها هنا. سيقوم محرك الذكاء الاصطناعي المحلي باستخراج البيانات فوراً.",
    parseSMSBtn: "تحليل الرسالة البنكية",
    parsedPreview: "معاينة البيانات المستخرجة",
    approveTx: "اعتماد وتسجيل المعاملة",
    ledgerRecords: "سجل المعاملات الموثقة",
    properties: "الخصائص",
    actions: "الإجراءات",
    linkBankBtn: "ربط حساب مصرف الإنماء (Open Banking)",
    linkingProgress: "جاري الاتصال بنظام المصرفية المفتوحة التابع لمصرف الإنماء...",
    linkedStatus: "الحسابات المربوطة:",
    
    // Subscriptions
    subsTitle: "رادار الاشتراكات المتكررة",
    subsDesc: "تحديد الاشتراكات ذات الفترات الثابتة، تتبع مواعيد التجديد التلقائي، واكتشاف الهدر المالي.",
    registerSub: "تسجيل اشتراك جديد",
    merchantName: "اسم التاجر/الخدمة",
    interval: "فترة التكرار",
    weekly: "أسبوعي",
    monthly: "شهري",
    yearly: "سنوي",
    nextRenewal: "التجديد القادم",
    utilityScore: "مؤشر المنفعة والمنفعة (0-1)",
    saveSub: "حفظ الاشتراك",
    subsRecommendations: "الاشتراكات الحالية وتوصيات رادار الإلغاء",
    lowUtilityCancel: "منفعة منخفضة: هل تفضل الإلغاء؟",
    utilityLevel: "مستوى المنفعة",
    refreshBtn: "تحديث الأسواق",
    renewalCountdown: "عداد التجديد",
    active: "نشط",
    paused: "متوقف",
    days: "أيام",

    // Simulator
    simTitle: "محاكي السيناريوهات المالية (ماذا لو؟)",
    simDesc: "توقع التأثير المالي طويل المدى على ميزانيتك قبل شراء سيارة، أخذ قرض، أو اتخاذ قرارات مالية كبيرة.",
    simVariables: "متغيرات السيناريو المالي",
    simName: "اسم القرار/السيناريو",
    oneTimeCost: "التكلفة المدفوعة مقدماً (ريال)",
    monthlyCostChange: "التغير في المصاريف الشهرية (ريال)",
    monthlyIncomeChange: "التغير في الدخل الشهري (ريال)",
    simHorizon: "المدى الزمني للمحاكاة",
    years1: "توقع لـ سنة واحدة",
    years3: "توقع لـ 3 سنوات",
    years5: "توقع لـ 5 سنوات",
    runProjections: "تشغيل المحاكاة المالية",
    projectedWorth: "مقارنة صافي القيمة المالية المستقبلية",
    decisionImpact: "تأثير القرار المالي",
    currentMonthlySavings: "الادخار الشهري الحالي",
    simulatedMonthlySavings: "الادخار الشهري بعد القرار",
    simPrompt: "أدخل متغيرات القرار في اللوحة الجانبية لتشغيل محرك إسقاطات القيمة المالية.",

    // Stock Advisor
    stockTitle: "متتبع الاستثمارات ومستشار الشرعيات",
    stockDesc: "تتبع قيمة محفظتك الاستثمارية، وزع الأصول، واطلع على إشارات البيع والشراء والشرعية محلياً.",
    portfolioVal: "القيمة السوقية للمحفظة",
    costBasis: "تكلفة الشراء الأساسية",
    unrealizedPnL: "الأرباح/الخسائر غير المحققة",
    registerAsset: "تسجيل أصل استثماري",
    symbol: "الرمز (رقم التداول)",
    assetName: "اسم الشركة",
    quantity: "الكمية",
    buyPrice: "سعر الشراء ($)",
    curPrice: "السعر الحالي في السوق ($)",
    addAssetBtn: "إضافة الأصل للمحفظة",
    assetAllocation: "توزيع المحفظة الاستثمارية",
    tradingSignals: "إشارات التداول والتحليل الفني ذكياً",
    signalsDesc: "حسابات فنية محلية بالكامل: تدمج مؤشرات القوة النسبية RSI وتقاطعات المتوسطات المتحركة SMA مع تحليل مشاعر عناوين الأخبار.",
    noSignals: "أضف أصولاً استثمارية لعرض الإشارات الفنية ونسب الشرعية.",
    shariahBadge: "حالة الشرعية",
    compliant: "متوافق شرعاً",
    nonCompliant: "غير متوافق شرعاً",
    complianceCheck: "معايير تصفية الأسهم والشرعية",
    complianceCheckDesc: "تحليل بنود الميزانية وفق معايير هيئة السوق المالية (Tadawul): نسبة الديون < 33%، نسبة النقد المالي المحرم < 33%، الدخل التطهيري < 5%.",

    // Savings Goals
    savingsTitle: "أهداف الادخار الذكي",
    savingsDesc: "أنشئ أهدافك المالية واحسب نسبة الادخار المرنة والمتكيفة مع تدفقاتك النقدية.",
    allocationAdvice: "توصية الادخار (رؤية السعودية 2030)",
    recommendedRate: "نسبة الادخار المرنة الموصى بها:",
    formulaExplanation: "حساب ديناميكي متكيف: يضبط نسبة الادخار الأساسية (20%) مقارنة بالدخل والمصاريف الثابتة الحالية، لحمايتك من السيولة المنخفضة في مواسم المصاريف العالية.",
    createTargetGoal: "إنشاء هدف ادخار جديد",
    goalTitle: "اسم الهدف المالي",
    currentSaved: "المبلغ المدخر حالياً (ريال)",
    saveGoalBtn: "حفظ الهدف المالي",
    trackedTargets: "أهداف وتحديات الادخار (رؤية 2030)",
    savedOf: "مدخر من إجمالي",
    addFunds: "شحن رصيد الهدف المالي ($)",
    fundGoalBtn: "شحن الهدف",
    noGoals: "لا توجد أهداف ادخارية نشطة. قم بإنشاء هدفك الأول في اللوحة الجانبية!",
    gamificationBadges: "تحديات وأوسمة الادخار الذكي",
    gamificationDesc: "تحديات مصممة لتعزيز ثقافة الادخار وزيادة ادخار الأسر السعودية إلى 10% تماشياً مع رؤية السعودية 2030.",
    unlockedAt: "تم الفوز به بتاريخ",
    locked: "مغلق"
  }
};
